# Load necessary libraries

In [13]:
import numpy as np

# Lecture

In [15]:
aList = [0, 1, 2, 4, 5]
type(aList)

list

In [19]:
listList = [3, ['3', '4', '5'], 5.5, [4, 5, 6]]
listList

[3, ['3', '4', '5'], 5.5, [4, 5, 6]]

In [21]:
listList = [3,               # a number
            ['3', '4', '5'], # a list of strings
            5.5,             # another float 
            [4, 5, 6]
           ]
listList

[3, ['3', '4', '5'], 5.5, [4, 5, 6]]

In [25]:
aList = [0, 1, 2, 4, 5]
sList = ['0', '1', '2', '4', '5']

aList + sList

[0, 1, 2, 4, 5, '0', '1', '2', '4', '5']

In [27]:
sList + sList

['0', '1', '2', '4', '5', '0', '1', '2', '4', '5']

In [29]:
sList * 3

['0', '1', '2', '4', '5', '0', '1', '2', '4', '5', '0', '1', '2', '4', '5']

In [31]:
aList * 3

[0, 1, 2, 4, 5, 0, 1, 2, 4, 5, 0, 1, 2, 4, 5]

In [39]:
aList_np = np.array(aList)
print(aList_np)

print(type(aList))
print(type(aList_np))

[0 1 2 4 5]
<class 'list'>
<class 'numpy.ndarray'>


In [44]:
print(aList)
print(aList_np)

[0, 1, 2, 4, 5]
[0 1 2 4 5]


In [64]:
# aList + 3

# TypeError: can only concatenate list (not "int") to list

In [60]:
aList + [3]

[0, 1, 2, 4, 5, 3]

In [62]:
aList_np * 3

array([ 0,  3,  6, 12, 15])

# Exercise - my solution

In [167]:
listList = [3, ['3', '4', '5'], 5.5, [4, 5, 6]]
listList

[3, ['3', '4', '5'], 5.5, [4, 5, 6]]

In [183]:
# for i in range(0, len(listList)):
#     print("List element %g is %g and is of type %s." %(i, listList[i], type(listList[i])))
    
# TypeError: must be real number, not list

In [179]:
for i in range(0, len(listList)):
    print(f"List element {i} is {listList[i]} and is of type {type(listList[i])}.")

List element 0 is 3 and is of type <class 'int'>.
List element 1 is ['3', '4', '5'] and is of type <class 'list'>.
List element 2 is 5.5 and is of type <class 'float'>.
List element 3 is [4, 5, 6] and is of type <class 'list'>.


In [185]:
for i in range(0, len(listList)):
    print(f"List element {i} is {listList[i]} and is of type {type(listList[i]).__name__}.")

List element 0 is 3 and is of type int.
List element 1 is ['3', '4', '5'] and is of type list.
List element 2 is 5.5 and is of type float.
List element 3 is [4, 5, 6] and is of type list.


# Exercise - course solution

In [202]:
listList = [3, ['3', '4', '5'], 5.5, [4, 5, 6]]
listList

[3, ['3', '4', '5'], 5.5, [4, 5, 6]]

In [214]:
for item in range(len(listList)):
    print(f'List element {item} is {listList[item]} and is of type of {type(item)}')

List element 0 is 3 and is of type of <class 'int'>
List element 1 is ['3', '4', '5'] and is of type of <class 'int'>
List element 2 is 5.5 and is of type of <class 'int'>
List element 3 is [4, 5, 6] and is of type of <class 'int'>


In [216]:
s = 'Mike'

for i, letter in enumerate(s):
    print(i, letter)

0 M
1 i
2 k
3 e


In [220]:
for idx, item in enumerate(listList):
    print(f'List element {idx} is {item} and is of type of {type(item)}')

List element 0 is 3 and is of type of <class 'int'>
List element 1 is ['3', '4', '5'] and is of type of <class 'list'>
List element 2 is 5.5 and is of type of <class 'float'>
List element 3 is [4, 5, 6] and is of type of <class 'list'>


In [236]:
for idx, item in enumerate(listList):
    t = str(type(item))[8:][:-2]
    
    print(f'List element {idx} is {item} and is of type of {t}.')

List element 0 is 3 and is of type of int.
List element 1 is ['3', '4', '5'] and is of type of list.
List element 2 is 5.5 and is of type of float.
List element 3 is [4, 5, 6] and is of type of list.


In [238]:
for idx, item in enumerate(listList):
    t = str(type(item))[8:]
    apost = t.find("'")
    
    print(f'List element {idx} is {item} and is of type of {t[:apost]}.')

List element 0 is 3 and is of type of int.
List element 1 is ['3', '4', '5'] and is of type of list.
List element 2 is 5.5 and is of type of float.
List element 3 is [4, 5, 6] and is of type of list.
